### ISSUE TITLE
issue playing in plexwebplayer

### ISSUE THREAD

**Issue by RavenB** [shopgirl284/RTUSA.bundle#3]
Hi,

currently the livefeeds (the shows do work) doesnt not work in the plexwebplayer (latest version) i get  cannot load M3U8 cross domain access denied .
Fix possible ? would be wonderfull

**Comment by shopgirl284** [comment]
Browsers using the PlexWeb client often have issues with HLS content. See https://forums.plex.tv/discussion/comment/1164642/#Comment_1164642 for more info
