### ISSUE TITLE
does not play on Android plexapp

### ISSUE THREAD

**Issue by RavenB** [shopgirl284/RTUSA.bundle#4]
Hi,

currently does not work on android plexapp for and videos and livefeed. (might be android problem ?)

**Comment by shopgirl284** [comment]
Android should work. But I will give it a look.

Also, you should be using the channel that is available from the Channel Directory instead of my version since it is now the official copy and will update automitically if there need to be fixes.

**Comment by shopgirl284** [comment]
It is working for me on the Android app.

But again make sure you install it from the channel directory, since there may be changes that are not reflected in my version

**Comment by RavenB** [comment]
hi,
removed the rt bundle and checked in channel directory. The rt plugin does not appear for me (anything special that needs to be done ?). 
Also tested on another android device and no playback.

**Comment by shopgirl284** [comment]
It should be in the Channel Directory. I do not see it either, so I am looking into why.

**Comment by shopgirl284** [comment]
Old issue closing
