### ISSUE TITLE
RT Feed Change

### ISSUE THREAD

**Issue by doczong** [shopgirl284/RTUSA.bundle#5]
Hey shopgirl,

The RT feed is broken, and I haven't pushed any changes, but this will fix all the live feeds, if you publish a new bundle with these changes all the feeds will work again (they weren't working for me in the Web client or on Roku).

Previous feeds offline as of August 1st, 2016
LIVE_FEED = 'https://rt-a.akamaihd.net/%s/master.m3u8'
LIVE_OPTIONS = [("RT News Live", "ch_01@325605"), ("RT USA Live", "ch_04@325608"), ("RT Documentary Live", "ch_05@325609"), ("RT UK Live", "ch_06@325610")]

LIVE_FEED = 'http://rt-eng-live.hls.adaptive.level3.net/rt/%s/index1600.m3u8'
LIVE_OPTIONS = [("RT News Live", "eng"), ("RT USA Live", "usa"), ("RT Documentary Live", "doc"), ("RT UK Live", "uk")]

**Comment by shopgirl284** [comment]
I have sent a PR request to the Plexinc-plugins repository, which is the official version for the Plex channel directory. See PR#6
