### ISSUE TITLE
Live channel does not play since plex 1.8.1

### ISSUE THREAD

**Issue by RavenB** [shopgirl284/RTUSA.bundle#7]
Prerecorded channels work but live channel doesnt work.

GO live channel -> select any live channel -> error will occur.

Either RT changed something or its the latest plexserver version.

**Comment by shopgirl284** [comment]
There is something very odd going on with the channel. I will look into it and report back once I have figured out the issue,

**Comment by shopgirl284** [comment]
Receiving the following error for all live feeds, though but there is no includeBandwidths anywhere in the code of the `__init__.py.`

`2017-08-27 14:31:56,710 (20a8) :  DEBUG (runtime:717) - Handling request GET /video/rtusa/createvideoclipobject?ch_m3u8=http%3A%2F%2Frt-eng-live.hls.adaptive.level3.net%2Frt%2Fusa%2Findex1600.m3u8&include_container=1&title=RT+USA+Live&includeBandwidths=1

2017-08-27 14:31:56,717 (20a8) :  DEBUG (runtime:814) - Found route matching /video/rtusa/createvideoclipobject

2017-08-27 14:31:56,717 (20a8) :  CRITICAL (core:574) - Exception (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-42bd8c63f\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
    result = f(**d)
TypeError: CreateVideoClipObject() got an unexpected keyword argument 'includeBandwidths'
`

**Comment by shopgirl284** [comment]
Error fixed by adding `kwargs`. But it appears RT has also changed the URL address of their live feeds, so it will take a little more research to fix completely.

**Comment by shopgirl284** [comment]
See https://github.com/plexinc-plugins/RTUSA.bundle/pull/4
